### ISSUE TITLE
Fix REPL

### ISSUE THREAD

**Issue by sinedie** [bryanmylee/svelte-previous#3]
Update the `usePrevious` change for v2 on the REPL

**Comment by bryanmylee** [comment]
Could you provide the steps to recreate the issue you are facing? `svelte-previous` is working on the REPL for me.

https://svelte.dev/repl/3d347bff1e5c4353869ae781f29b2fc4?version=3.38.2

**Comment by sinedie** [comment]
Oh yeah, it works, just that the link in the readme is outdated.

**Comment by bryanmylee** [comment]
Ah gotcha 👍  Fixed!
