### ISSUE TITLE
Syntax error with v2.0.1

### ISSUE THREAD

**Issue by mhatvan** [bryanmylee/svelte-previous#4]
I just updated from v2.0.0 to v2.0.1 and my code breaks with the following error:

`client.ts:33 SyntaxError: The requested module '/node_modules/.vite/svelte-previous.js?v=46a34aac' does not provide an export named 'withPrevious'`

I was using `usePrevious` before and switched to `withPrevious`. When switching back to deprecated `usePrevious`, the code works as expected.

**Comment by bryanmylee** [comment]
Can you help me check if it's a caching issue? Try removing `node_modules` and re-installing your dependencies again.

I'm not able to reproduce the issue, even with the REPL.

**Comment by mhatvan** [comment]
Seems to be a caching issue indeed, cannot reproduce it anymore either. Thank you!
